version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing hestia"
      - pip3 install pytest

  build:
    commands:
      - echo "Building hestia"
      - python -m pytest

  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo Build completed; else echo Build failed ignoring manual approval; fi
      - echo "build completed on `date`."

# the actual location of artifacts are defined in CodeBuild -> Artifact
artifacts:
  files:
    - "**/*"
    
