version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing hestia"
      - pip3 install pytest
  build:
    commands:
      - echo "Building hestia"
      - python -m pytest

