# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import my_tools.storage_engine


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('matter_contract', 'Matter Contract'), ('matter_deed', 'Matter Deed'), ('matter_notice', 'Matter Notice'), ('matter_letter', 'Matter Letter')], max_length=32)),
                ('related_model_id', models.PositiveIntegerField(default=0)),
                ('uuid', models.CharField(default='', max_length=32, unique=True)),
                ('file', models.FileField(blank=True, max_length=255, storage=django.core.files.storage.FileSystemStorage(location=b'/var/www/myhestia.doc/'), upload_to=my_tools.storage_engine.make_file_path)),
                ('file_ext', models.CharField(default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('md_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='md_thumbnail_files', to='core.GlobalFile')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_files', to='core.GlobalFile')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('S', 'Staff'), ('A', 'Sys Admin')], default='S', max_length=1)),
                ('is_team_head', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], default='A', max_length=1)),
                ('en_nickname', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=8)),
                ('mobile', models.CharField(default='', max_length=32)),
                ('personal_email', models.CharField(blank=True, default='', max_length=128)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_members', to='core.Staff')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(31, 'Accounting Manager'), (32, 'Accountant'), (21, 'Business Manager'), (22, 'Business Admin'), (1, 'Managing Director')])),
                ('is_active', models.BooleanField(default=False)),
                ('hr_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='core.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_teams', to='core.StaffTeam')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.StaffTeam'),
        ),
    ]
