# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffposition',
            name='position',
            field=models.IntegerField(choices=[(21, 'Business Manager'), (1, 'Managing Director')]),
        ),
    ]
