# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170214_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfile',
            name='file_type',
            field=models.CharField(choices=[('manual_attachment', 'Manual Attachment'), ('matter_contract', 'Matter Contract'), ('matter_deed', 'Matter Deed'), ('matter_notice', 'Matter Notice'), ('matter_letter', 'Matter Letter')], max_length=32),
        ),
    ]
