# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_datetime', models.DateTimeField()),
                ('logout_datetime', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('expire_type', models.CharField(choices=[('e', 'Time Expired'), ('l', 'Logged Out'), ('k', 'Kicked Out'), ('lk', 'Login Kicked Out')], default='e', max_length=2)),
                ('is_latest', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='core.Staff')),
            ],
        ),
    ]
