# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='en_nickname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
