# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Matter')], default='M', max_length=1)),
                ('type_name', models.CharField(choices=[('Contract', 'Contract'), ('Deed', 'Deed'), ('Notice', 'Notice'), ('Letter', 'Letter')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Matter')], default='M', max_length=1)),
                ('receiver', models.CharField(choices=[('Client', 'Client'), ('Staff', 'Staff'), ('Agent', 'Agent')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='', max_length=64, unique=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'In Use'), ('IA', 'Not In Use')], default='A', max_length=8)),
                ('send_type', models.CharField(choices=[('SMS', 'SMS'), ('EM', 'Email')], default='EM', max_length=4)),
                ('category', models.CharField(blank=True, choices=[('MPO', 'Purchase Off-Plan Property (Matter)'), ('MPE', 'Purchase Existing Property (Matter)'), ('MSE', 'Sell Existing Property (Matter)')], default='', max_length=8)),
                ('trigger', models.CharField(blank=True, choices=[('EXC', 'Contract Exchange'), ('SDD', 'Stamp Duty Due'), ('SET', 'Settlement')], default='', max_length=8)),
                ('trigger_days', models.SmallIntegerField(default=0)),
                ('subject', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.TextField()),
                ('attachments', models.ManyToManyField(blank=True, related_name='attachment_n_templates', to='n_template.AttachmentType')),
                ('cc_tos', models.ManyToManyField(blank=True, related_name='cc_to_n_templates', to='n_template.NReceiver')),
                ('send_tos', models.ManyToManyField(blank=True, related_name='send_to_n_templates', to='n_template.NReceiver')),
            ],
        ),
    ]
