# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nreceiver',
            name='receiver',
            field=models.CharField(choices=[('Client', 'Client'), ('Staff', 'Staff'), ('Agent', 'Agent'), ('Solicitor/Conveyancer', 'Solicitor/Conveyancer')], max_length=64),
        ),
    ]
