# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('sent_out_time', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.SmallIntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[(b'S', b'Sent'), (b'P', b'Pending'), (b'R', b'Resending'), (b'F', b'Failure to send'), (b'C', b'Cancelled')], default=b'P', max_length=8)),
                ('subject', models.CharField(max_length=128)),
                ('to_email', models.TextField()),
                ('cc_email', models.TextField(blank=True, default=b'')),
                ('bcc_email', models.TextField(blank=True, default=b'')),
                ('from_email', models.TextField(blank=True, default=b'')),
                ('from_email_desc', models.CharField(blank=True, default=b'', max_length=64)),
                ('text_content', models.TextField(blank=True, default=b'')),
                ('html_content', models.TextField(blank=True, default=b'')),
                ('no_reply', models.BooleanField(default=False)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_list', models.TextField(blank=True, default=b'')),
                ('attach_file_list', models.TextField(blank=True, default=b'')),
                ('failure_log', models.TextField(blank=True, default=b'')),
            ],
            options={
                'verbose_name': 'Multipart Email',
                'verbose_name_plural': 'Multipart Emails',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'P', b'Pending'), (b'S', b'Sent'), (b'F', b'Fail'), (b'C', b'Cancel')], default=b'P', max_length=8)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('sms_priority', models.CharField(default=b'M', max_length=8)),
                ('sms_from', models.CharField(blank=True, max_length=32, null=True)),
                ('sms_subject', models.CharField(blank=True, max_length=32, null=True)),
                ('sms_text', models.CharField(max_length=1024)),
                ('target_numbers', models.CharField(max_length=4096)),
                ('sp_response', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Result')),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMSs',
            },
        ),
    ]
