"""
Django settings for myhestia project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import platform

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import socket

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%h4n6zm_6gp#y$v-*j9+vre^3vkr4rwvg3vs^@0u4o2h4s)0(z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['linklawyer.myhestia.com.au', '*']

if socket.gethostname().lower().startswith('linklawyer'):
    DEBUG = False
    ALLOWED_HOSTS = ['*']
    SERVER_BADGE = '<span></span>'
else:
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    SERVER_BADGE = '<span style="color: red;">[Test Server]</span>'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'debug_toolbar',
    # 'debug_panel',
    'messaging.apps.MessagingConfig',

    'login.apps.LoginAppConfig',
    'agent.apps.AgentConfig',
    'core.apps.CoreConfig',
    'clientdb.apps.ClientdbConfig',
    'matters.apps.MattersConfig',
    'n_template.apps.TemplateConfig',
    'project.apps.ProjectConfig',
    'my_bill.apps.MyBillConfig',
]

MIDDLEWARE_CLASSES = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'debug_panel.middleware.DebugPanelMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'my_tools.middleware.SessionExpireMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',

                'my_tools.template_context_processor.global_vars',
            ],
            'builtins': ['my_tools.template_tag', 'my_tools.template_tag_app'],
        },
    },
]

# Database
if platform.system() == 'Darwin':
    DB_OPTION_DICT = {}
else:
    DB_OPTION_DICT = {
        'init_command': 'SET default_storage_engine=InnoDB',
    }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myhestia',
        'USER': 'myhestia',
        'PASSWORD': 'myhestia',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': DB_OPTION_DICT
    }
}


#
# Internationalization
#
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Australia/Sydney'
USE_I18N = True
USE_L10N = False
USE_TZ = False

#
# date format
#
DATE_FORMAT = 'd-m-Y'
DATETIME_FORMAT = 'd-m-Y H:i:s'
DATE_INPUT_FORMATS = [
    '%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y'
]


#
# Static files (CSS, JavaScript, Images)
#
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/myhestia.static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'media'),
)

DOC_FILE_ROOT = '/var/www/myhestia.doc/'
TMP_FILE_ROOT = '/var/www/myhestia.tmp/'

#
# urls
#
ROOT_URLCONF = 'myhestia.urls'
WSGI_APPLICATION = 'myhestia.wsgi.application'


#
# customized user login
#
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'

AUTHENTICATION_BACKENDS = ('login.models.UserLoginBackend',)


#
# sessions
#
SESSION_COOKIE_NAME = 'my_hestia_session_back_office'

# seconds
SESSION_IDLE_TIMEOUT = 60 * 60

# session time out when browser closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


#
# debug toolbar
#
DEBUG_TOOLBAR_PATCH_SETTINGS = False
INTERNAL_IPS = ('127.0.0.1',)
