# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientdb', '0001_initial'),
        ('n_template', '0001_initial'),
        ('agent', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('matter_contract', 'Matter Contract'), ('matter_deed', 'Matter Deed'), ('matter_notice', 'Matter Notice'), ('matter_letter', 'Matter Letter')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('global_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gf_matter_docs', to='core.GlobalFile')),
            ],
        ),
        migrations.CreateModel(
            name='MatterNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False)),
                ('send_type', models.CharField(choices=[('SMS', 'SMS'), ('EM', 'Email')], default='EM', max_length=4)),
                ('expect_sent_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('W', 'Waiting To Send'), ('S', 'Sent'), ('I', 'Inactive')], default='W', max_length=1)),
                ('subject', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.TextField()),
                ('template_category', models.CharField(blank=True, choices=[('MPO', 'Purchase Off-Plan Property (Matter)'), ('MPE', 'Purchase Existing Property (Matter)'), ('MSE', 'Sell Existing Property (Matter)')], default='', max_length=8)),
                ('template_trigger', models.CharField(blank=True, choices=[('EXC', 'Contract Exchange'), ('SDD', 'Stamp Duty Due'), ('SET', 'Settlement')], default='', max_length=8)),
                ('template_trigger_days', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='attachment_mns', to='n_template.AttachmentType')),
                ('cc_tos', models.ManyToManyField(blank=True, related_name='cc_to_mns', to='n_template.NReceiver')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mns', to='core.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='MatterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_num', models.CharField(blank=True, default='', max_length=64)),
                ('matter_type', models.CharField(choices=[('POP', 'Purchase Off-Plan Property'), ('PEP', 'Purchase Existing Property'), ('SEP', 'Sell Existing Property'), ('OT', 'Other')], max_length=8)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], default='A', max_length=1)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('property_street', models.CharField(blank=True, default='', max_length=255)),
                ('property_suburb', models.CharField(blank=True, default='', max_length=64)),
                ('property_postcode', models.CharField(blank=True, default='', max_length=16)),
                ('property_state', models.CharField(blank=True, choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queens Land'), ('TAS', 'Tasmania'), ('SA', 'South Australia'), ('WA', 'West Australia'), ('NT', 'Northern Territory')], default='', max_length=32)),
                ('stamp_duty_amount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=12, null=True)),
                ('stamp_duty_due_date', models.DateField(blank=True, null=True)),
                ('stamp_duty_paid_date', models.DateField(blank=True, null=True)),
                ('contract_exchange_date', models.DateField(blank=True, null=True)),
                ('cooling_off_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('matter_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_contact_matters', to='agent.AgentContact')),
                ('clients', models.ManyToManyField(related_name='client_matters', to='clientdb.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matters', to='core.Staff')),
                ('matter_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_matters', to='core.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='matternotification',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mns', to='matters.MatterRecord'),
        ),
        migrations.AddField(
            model_name='matternotification',
            name='send_tos',
            field=models.ManyToManyField(blank=True, related_name='send_to_mns', to='n_template.NReceiver'),
        ),
        migrations.AddField(
            model_name='matternotification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_template_mns', to='n_template.NTemplate'),
        ),
        migrations.AddField(
            model_name='matternotification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_mns', to='core.Staff'),
        ),
        migrations.AddField(
            model_name='matterdocument',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_docs', to='matters.MatterRecord'),
        ),
    ]
