# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterrecord',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Closed'), ('P', 'Stamp Duty Paid')], default='A', max_length=1),
        ),
    ]
