# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0003_auto_20170311_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterrecord',
            name='solicitor_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='matterrecord',
            name='solicitor_mobile',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='matterrecord',
            name='solicitor_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
