# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('core', '0003_auto_20170315_1651'),
        ('matters', '0004_auto_20170311_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='matternotification',
            name='manual_attachment_gfs',
            field=models.ManyToManyField(blank=True, related_name='manual_attachment_gf_mns', to='core.GlobalFile'),
        ),
        migrations.AddField(
            model_name='matterrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_matters', to='project.Project'),
        ),
    ]
