# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0006_auto_20170317_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='matterrecord',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
